# Generated by Django 5.2.6 on 2025-09-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('numero_bac', models.CharField(blank=True, max_length=50, null=True)),
                ('nni', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('fonction_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
