# Generated by Django 5.2.6 on 2025-09-20 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fonction_mere',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fonction_pere',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nom_mere',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prenom_mere',
        ),
        migrations.RemoveField(
            model_name='student',
            name='prenom_pere',
        ),
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_actuel', models.CharField(blank=True, max_length=50, null=True)),
                ('semestre', models.CharField(blank=True, max_length=20, null=True)),
                ('annee_s1', models.IntegerField(blank=True, null=True)),
                ('validation_s1', models.BooleanField(default=False)),
                ('releve_s1', models.FileField(blank=True, null=True, upload_to='documents/academics/')),
                ('attestation_s1', models.FileField(blank=True, null=True, upload_to='documents/academics/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.FloatField(blank=True, null=True)),
                ('tour_poitrine', models.FloatField(blank=True, null=True)),
                ('tour_ceinture', models.FloatField(blank=True, null=True)),
                ('tour_taille', models.FloatField(blank=True, null=True)),
                ('tour_bassin', models.FloatField(blank=True, null=True)),
                ('tour_cou', models.FloatField(blank=True, null=True)),
                ('longueur_manche', models.FloatField(blank=True, null=True)),
                ('longueur_dos', models.FloatField(blank=True, null=True)),
                ('longueur_cote', models.FloatField(blank=True, null=True)),
                ('pointure', models.FloatField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pro', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_perso', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_parent1', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_parent2', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('cin', "Carte d'identité"), ('naissance', 'Acte de naissance'), ('bac', 'Diplôme du Bac'), ('licence', 'Diplôme Licence'), ('photo1', 'Photo militaire'), ('photo2', 'Photo civile'), ('photo3', 'Photo militaire intégrale'), ('autre', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='documents/students/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5, null=True)),
                ('assureur', models.CharField(blank=True, max_length=100, null=True)),
                ('num_assure', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('maladies_chroniques', models.TextField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment', models.CharField(blank=True, max_length=50, null=True)),
                ('etage', models.CharField(blank=True, max_length=20, null=True)),
                ('aile', models.CharField(blank=True, max_length=20, null=True)),
                ('chambre', models.CharField(blank=True, max_length=20, null=True)),
                ('lit', models.CharField(blank=True, max_length=20, null=True)),
                ('responsable_chambre', models.BooleanField(default=False)),
                ('responsable_aile', models.BooleanField(default=False)),
                ('responsable_etage', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMilitary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(blank=True, max_length=50, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('sport', models.CharField(choices=[('foot', 'Football'), ('course', 'Course'), ('marche', 'Marche'), ('natation', 'Natation'), ('voley', 'Volley'), ('aucun', 'Pas de sport')], default='aucun', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military', to='students.student')),
            ],
        ),
    ]
