# Generated by Django 5.2.6 on 2025-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_fonction_mere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentacademic',
            name='departement',
            field=models.CharField(blank=True, choices=[('IRT', 'IRT'), ('SID', 'SID'), ('MPG', 'MPG'), ('GC', 'GC'), ('GM', 'GM'), ('GE', 'GE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='niveau_actuel',
            field=models.CharField(blank=True, choices=[('1ère année', '1ère année'), ('2e année', '2e année'), ('3eme année', '3eme année')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademic',
            name='semestre',
            field=models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S3 DD', 'S3 DD'), ('S4DD', 'S4DD'), ('S5DD', 'S5DD'), ('S5', 'S5'), ('S5E', 'S5E'), ('S6DD', 'S6DD'), ('S6', 'S6')], max_length=20, null=True),
        ),
    ]
